<?php

namespace Database\Seeders;

use App\Actions\ProvisionVisaTypeDefaultsAction;
use App\Models\TargetCountry;
use App\Models\VisaType;
use Illuminate\Database\Seeder;

class AdditionalVisaCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $provisionDefaults = app(ProvisionVisaTypeDefaultsAction::class);

        foreach ($this->catalogs() as $countrySlug => $catalog) {
            $country = TargetCountry::query()->updateOrCreate(
                ['slug' => $countrySlug],
                ['name' => $catalog['country'], 'is_active' => true],
            );

            foreach ($catalog['visas'] as $visa) {
                $visaType = VisaType::query()->updateOrCreate(
                    [
                        'target_country_id' => $country->id,
                        'slug' => $visa['slug'],
                    ],
                    [
                        'name' => $visa['name'],
                        'code' => $visa['code'],
                        'official_subclass' => $visa['official_subclass'],
                        'is_active' => true,
                        'submission_sla_days' => $visa['submission_sla_days'],
                        'decision_sla_days' => $visa['decision_sla_days'],
                        'validity_months' => $visa['validity_months'],
                        'stay_duration_days' => $visa['stay_duration_days'],
                        'entry_type' => $visa['entry_type'],
                        'service_scope' => $visa['service_scope'],
                        'priority_support' => $visa['priority_support'],
                        'dependants_allowed' => $visa['dependants_allowed'],
                        'biometrics_required' => $visa['biometrics_required'],
                        'interview_required' => $visa['interview_required'],
                        'medical_required' => $visa['medical_required'],
                        'police_clearance_required' => $visa['police_clearance_required'],
                        'financial_proof_required' => $visa['financial_proof_required'],
                        'checklist_intro' => $visa['checklist_intro'],
                        'portal_guidance' => $visa['portal_guidance'],
                        'notes' => $visa['notes'],
                        'official_reference_url' => $visa['official_reference_url'],
                        'official_summary' => $visa['official_summary'],
                        'official_requirements' => $visa['official_requirements'],
                    ],
                );

                $provisionDefaults->execute($visaType);
            }
        }
    }

    private function catalogs(): array
    {
        return [
            'south-korea' => [
                'country' => 'South Korea',
                'prefix' => 'KR',
                'reference_note' => 'Seeded from the Korea Visa Portal and related official Korean government visa guidance.',
                'visas' => [
                    $this->makeVisa('KR', [
                        'name' => 'Short-Term General',
                        'subclass' => 'C-3-1',
                        'summary' => 'Short-stay visa for general temporary visits to South Korea.',
                        'url' => 'https://www.visa.go.kr/openPage.do?LLANG=EN&MENU_ID=10204',
                        'entry_type' => 'single_entry',
                        'stay_duration_days' => 90,
                        'requirements' => [
                            'Hold a valid passport and apply for a short-term general stay purpose.',
                            'Show the visit is temporary and consistent with the declared travel plan.',
                            'Provide accommodation, itinerary, and financial support documents when requested.',
                            'Complete identity and document checks through the Korean diplomatic mission.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Medical Tourist',
                        'subclass' => 'C-3-3',
                        'summary' => 'Short-term visa for applicants visiting South Korea for approved medical tourism purposes.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020117',
                        'entry_type' => 'single_entry',
                        'stay_duration_days' => 90,
                        'medical_required' => true,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Show a confirmed medical tourism or treatment purpose through a recognized channel where required.',
                            'Provide passport, treatment plan, and hospital or facilitator documentation.',
                            'Demonstrate funds for treatment, living costs, and return travel.',
                            'Complete identity and supporting document review at the Korean mission.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Business Visitor (General)',
                        'subclass' => 'C-3-4',
                        'summary' => 'Short-term business visa for invited business visitors attending permitted commercial activities.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020117',
                        'entry_type' => 'multiple_entry',
                        'stay_duration_days' => 90,
                        'requirements' => [
                            'Provide an invitation or business purpose consistent with short-term visitor activity.',
                            'Show the trip is limited to permitted meetings, consultations, or similar activities.',
                            'Submit passport, employer documents, and Korean company or host details as required.',
                            'Demonstrate intent to leave South Korea after the temporary visit.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Short-Term Employee',
                        'subclass' => 'C-4',
                        'summary' => 'Temporary visa for short-term work or project activity approved under Korean rules.',
                        'url' => 'https://www.visa.go.kr/openPage.do?LLANG=EN&MENU_ID=10204',
                        'entry_type' => 'single_entry',
                        'service_scope' => 'multi_step_case',
                        'stay_duration_days' => 90,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Show the planned work fits the short-term employee category and timeframe.',
                            'Provide sponsor or host documents from the Korean side.',
                            'Submit documents proving the applicant’s role, experience, and assignment terms.',
                            'Complete identity and eligibility checks before issuance.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Student',
                        'subclass' => 'D-2',
                        'summary' => 'Long-stay student visa for degree study at an approved Korean educational institution.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020501',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 48,
                        'stay_duration_days' => 1460,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Provide admission or enrollment documents from an eligible Korean institution.',
                            'Show funds for tuition, living costs, and settlement in Korea.',
                            'Submit passport, academic records, and any mission-specific study documents.',
                            'Complete identity and eligibility checks for the intended course of study.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Korean Language Trainee',
                        'subclass' => 'D-4-1',
                        'summary' => 'Long-stay visa for Korean language training at an approved institution.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020501',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Provide acceptance documents for an approved Korean language course.',
                            'Show funds for tuition, living costs, and return or onward travel.',
                            'Submit educational background and identity documents required by the mission.',
                            'Complete identity and eligibility checks for long-stay training.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Job Seeker',
                        'subclass' => 'D-10',
                        'summary' => 'Long-stay visa for eligible applicants seeking work or preparing for specific professional activity in Korea.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020117',
                        'entry_type' => 'multiple_entry',
                        'validity_months' => 12,
                        'stay_duration_days' => 365,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Show an eligible background for job-seeking or start-up preparation under Korean rules.',
                            'Provide education, experience, and career planning evidence.',
                            'Demonstrate funds for living costs during the search period.',
                            'Meet identity and supporting document requirements set by the Korean mission.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Professor',
                        'subclass' => 'E-1',
                        'summary' => 'Work visa for professors teaching or researching at Korean higher education institutions.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020117',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'financial_proof_required' => false,
                        'requirements' => [
                            'Provide a qualifying appointment, contract, or sponsorship from a Korean institution.',
                            'Show relevant academic qualifications and professional credentials.',
                            'Submit passport, employment documents, and any mission-specific supporting evidence.',
                            'Complete identity and eligibility review for the academic appointment.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Foreign Language Instructor',
                        'subclass' => 'E-2',
                        'summary' => 'Work visa for teaching a foreign language at an approved Korean employer or educational institution.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020501',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'medical_required' => true,
                        'police_clearance_required' => true,
                        'requirements' => [
                            'Provide a valid teaching contract with an eligible Korean employer or school.',
                            'Submit required academic credentials and nationality-specific teaching documents if applicable.',
                            'Provide criminal history and health-related documents when required.',
                            'Complete identity and employment eligibility checks before issuance.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Researcher',
                        'subclass' => 'E-3',
                        'summary' => 'Work visa for qualified researchers invited by Korean institutions or employers.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020117',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'requirements' => [
                            'Provide a research appointment or invitation from an eligible Korean organization.',
                            'Show relevant academic, scientific, or technical qualifications.',
                            'Submit project or employment documents supporting the Korean research role.',
                            'Complete identity and eligibility checks for the assigned activity.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Foreign National of Special Ability',
                        'subclass' => 'E-7',
                        'summary' => 'Work visa for professionals taking approved specialty roles in South Korea.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020117',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 36,
                        'stay_duration_days' => 1095,
                        'dependants_allowed' => true,
                        'police_clearance_required' => true,
                        'requirements' => [
                            'Provide an eligible Korean job offer in a specialty occupation.',
                            'Show relevant academic background, experience, or licensing for the role.',
                            'Submit sponsor documents and employment terms from the Korean employer.',
                            'Meet identity, character, and supporting document requirements for the work category.',
                        ],
                    ]),
                    $this->makeVisa('KR', [
                        'name' => 'Marriage Migrant',
                        'subclass' => 'F-6',
                        'summary' => 'Residence visa for spouses of Korean nationals and certain family-based applicants.',
                        'url' => 'https://www.visa.go.kr/openPage.do?MENU_ID=1020117',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'medical_required' => true,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Provide valid marriage and family relationship evidence under Korean rules.',
                            'Show the relationship is genuine and meets family immigration requirements.',
                            'Submit sponsor identity, residence, and financial support documents where required.',
                            'Complete identity, background, and any health-related checks requested.',
                        ],
                    ]),
                ],
            ],
            'ireland' => [
                'country' => 'Ireland',
                'prefix' => 'IE',
                'reference_note' => 'Seeded from Immigration Service Delivery guidance and linked official Irish immigration pages.',
                'visas' => [
                    $this->makeVisa('IE', [
                        'name' => 'Short Stay Visit (Tourist)',
                        'subclass' => 'C Visit',
                        'summary' => 'Short-stay visitor permission for temporary tourism or personal visits in Ireland.',
                        'url' => 'https://www.irishimmigration.ie/short-stay-visas-policy/',
                        'entry_type' => 'single_entry',
                        'stay_duration_days' => 90,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Show the visit is temporary and within the permitted short-stay purpose.',
                            'Provide travel plans, accommodation details, and passport documents.',
                            'Demonstrate strong ties outside Ireland and intent to leave after the visit.',
                            'Show enough funds for the trip and return or onward travel.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Short Stay Business',
                        'subclass' => 'C Business',
                        'summary' => 'Short-stay business visa for meetings, negotiations, and limited approved business activity.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-work-in-ireland/what-are-my-options-for-working-in-ireland/coming-to-work-for-less-than-90-days/short-stay-business-visa/',
                        'entry_type' => 'single_entry',
                        'stay_duration_days' => 90,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Provide a genuine business purpose such as meetings or contract-related activity.',
                            'Show supporting documents from the Irish host or employer.',
                            'Stay within the short-stay business conditions, including work limits.',
                            'Demonstrate funds, travel plans, and intent to leave after the visit.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Short Stay Study',
                        'subclass' => 'C Study',
                        'summary' => 'Short-stay visa for study of 90 days or less in Ireland.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-study-in-ireland/what-are-my-study-visa-options/',
                        'entry_type' => 'single_entry',
                        'stay_duration_days' => 90,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Show acceptance on an eligible short course or study activity.',
                            'Provide passport, course details, and payment or enrolment documents.',
                            'Demonstrate funds for tuition, stay, and return travel.',
                            'Show the stay will remain temporary and within the short-study conditions.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Long Stay Study',
                        'subclass' => 'D Study',
                        'summary' => 'Long-stay study permission for students staying more than 90 days in Ireland.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-study-in-ireland/what-are-my-study-visa-options/',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'financial_proof_required' => true,
                        'medical_required' => true,
                        'requirements' => [
                            'Provide a letter of enrolment for an eligible programme.',
                            'Show required tuition payment and financial capacity for living costs.',
                            'Hold or arrange any required private medical insurance and registration steps.',
                            'Apply for the correct long-stay study route before travel if visa required.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Employment Visa',
                        'subclass' => 'D Employment',
                        'summary' => 'Long-stay employment visa for approved workers coming to Ireland with a qualifying permit or permission.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-work-in-ireland/what-are-my-work-visa-options/applying-for-a-long-stay-employment-visa/employment-visa/',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'requirements' => [
                            'Obtain the relevant Irish employment permit or approved work permission first.',
                            'Provide passport, contract, permit, and Irish employer documents.',
                            'Apply for a long-stay employment visa before travel if visa required.',
                            'Register after arrival if staying longer than 90 days.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Critical Skills Employment',
                        'subclass' => 'Critical Skills',
                        'summary' => 'Work route for applicants holding a Critical Skills Employment Permit in Ireland.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-work-in-ireland/what-are-my-options-for-working-in-ireland/coming-to-work-for-more-than-90-days/',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'requirements' => [
                            'Hold an approved Critical Skills Employment Permit.',
                            'Provide the permit, employment contract, and Irish employer information.',
                            'Meet the conditions linked to the eligible occupation and permit structure.',
                            'Apply for the long-stay work visa before travel if visa required.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'General Employment',
                        'subclass' => 'General Employment',
                        'summary' => 'Work route for applicants holding a General Employment Permit in Ireland.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-work-in-ireland/what-are-my-options-for-working-in-ireland/coming-to-work-for-more-than-90-days/',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'requirements' => [
                            'Hold an approved General Employment Permit.',
                            'Provide the permit, job offer, and Irish employer details.',
                            'Meet the permit-related occupation and employment conditions.',
                            'Apply for the long-stay work visa before travel if visa required.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Atypical Working Scheme',
                        'subclass' => 'AWS',
                        'summary' => 'Permission for specialized short-term work not covered by the standard employment permit system.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-work-in-ireland/what-are-my-work-visa-options/applying-for-a-long-stay-employment-visa/atypical-working-scheme/',
                        'entry_type' => 'single_entry',
                        'service_scope' => 'multi_step_case',
                        'stay_duration_days' => 90,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Obtain approval under the Atypical Working Scheme first.',
                            'Show the role is short term or otherwise within AWS-supported categories.',
                            'Provide approval letter, host documents, and travel identity documents.',
                            'Apply for the matching visa route before travel if visa required.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Join Family',
                        'subclass' => 'D Join Family',
                        'summary' => 'Long-stay family reunification visa for eligible non-EEA family members joining sponsors in Ireland.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-join-family-in-ireland/joining-an-irish-national/join-family-visa/',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Have an eligible sponsor in Ireland and a qualifying family relationship.',
                            'Provide relationship evidence and sponsor status documents.',
                            'Meet any policy requirements around dependency, sponsorship, or waiting periods.',
                            'Apply for the long-stay family route or preclearance route as required.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Start-up Entrepreneur Programme',
                        'subclass' => 'STEP',
                        'summary' => 'Residence permission for innovative entrepreneurs establishing a qualifying business in Ireland.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-work-in-ireland/what-are-my-options-for-working-in-ireland/coming-to-work-for-more-than-90-days/start-up-entrepreneur-programme-step/',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Propose an innovative start-up that fits the STEP rules.',
                            'Provide business plan, funding evidence, and character documentation.',
                            'Meet programme-specific entrepreneur and venture requirements.',
                            'Follow the STEP application process before travel or residence steps.',
                        ],
                    ]),
                    $this->makeVisa('IE', [
                        'name' => 'Visiting Academic',
                        'subclass' => 'Visiting Academic',
                        'summary' => 'Permission for certain academics or researchers coming to Ireland for a limited academic stay.',
                        'url' => 'https://www.irishimmigration.ie/coming-to-work-in-ireland/what-are-my-options-for-working-in-ireland/coming-to-work-for-more-than-90-days/visiting-academic/',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 12,
                        'stay_duration_days' => 365,
                        'financial_proof_required' => true,
                        'requirements' => [
                            'Have an eligible academic or research arrangement in Ireland for less than 12 months.',
                            'Show financial support from outside the State or through the sponsor arrangement.',
                            'Provide institution documents, identity documents, and stay details.',
                            'Stay within the visiting academic conditions, including work limitations where applicable.',
                        ],
                    ]),
                ],
            ],
            'united-kingdom' => [
                'country' => 'United Kingdom',
                'prefix' => 'UK',
                'reference_note' => 'Seeded from current GOV.UK visa guidance. This catalog represents the United Kingdom, not England as a separate immigration system.',
                'visas' => [
                    $this->makeVisa('UK', [
                        'name' => 'Standard Visitor',
                        'subclass' => 'Standard Visitor',
                        'summary' => 'Visitor route for tourism, family visits, short study, and certain permitted business or personal activities.',
                        'url' => 'https://www.gov.uk/standard-visitor',
                        'entry_type' => 'multiple_entry',
                        'stay_duration_days' => 180,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Show the visit is for permitted visitor activities only.',
                            'Demonstrate intent to leave the UK at the end of the visit.',
                            'Show enough money for the trip, stay, and return or onward travel.',
                            'Provide passport, travel history, and supporting documents as required.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Marriage Visitor',
                        'subclass' => 'Marriage Visitor',
                        'summary' => 'Visitor route for applicants coming to the UK to marry, form a civil partnership, or give notice.',
                        'url' => 'https://www.gov.uk/marriage-visa',
                        'entry_type' => 'single_entry',
                        'stay_duration_days' => 180,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Show the applicant is coming to the UK to marry, form a civil partnership, or give notice.',
                            'Demonstrate the relationship is genuine and the event is planned in the UK.',
                            'Show the applicant will leave the UK after the permitted visit.',
                            'Provide identity, venue, and relationship documents as required.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Student',
                        'subclass' => 'Student',
                        'summary' => 'Study route for applicants aged 16 or over attending an eligible course with a licensed sponsor.',
                        'url' => 'https://www.gov.uk/student-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 60,
                        'stay_duration_days' => 1825,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Hold an offer from a licensed student sponsor and a valid CAS where required.',
                            'Show enough money to support yourself and pay for the course.',
                            'Meet the English language requirement and any age-related consent rules.',
                            'Provide passport, supporting academic documents, and other evidence requested by UKVI.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Child Student',
                        'subclass' => 'Child Student',
                        'summary' => 'Study route for children aged 4 to 17 attending an independent school in the UK.',
                        'url' => 'https://www.gov.uk/child-study-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 60,
                        'stay_duration_days' => 1825,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Have an unconditional offer from an independent school in the UK.',
                            'Show suitable care and living arrangements in the UK.',
                            'Provide parental or guardian consent and financial support evidence.',
                            'Submit passport and required student documents during the UKVI process.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Skilled Worker',
                        'subclass' => 'Skilled Worker',
                        'summary' => 'Main sponsored work route for eligible jobs with approved UK employers.',
                        'url' => 'https://www.gov.uk/skilled-worker-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 60,
                        'stay_duration_days' => 1825,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Have a job offer from an approved UK sponsor.',
                            'Hold a valid certificate of sponsorship for an eligible occupation.',
                            'Meet the salary and English language requirements for the route.',
                            'Provide passport and route-specific supporting evidence through UKVI.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Health and Care Worker',
                        'subclass' => 'Health and Care Worker',
                        'summary' => 'Sponsored work route for eligible health and adult social care professionals.',
                        'url' => 'https://www.gov.uk/health-care-worker-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 60,
                        'stay_duration_days' => 1825,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'police_clearance_required' => true,
                        'requirements' => [
                            'Have an eligible health or care job with an approved UK employer.',
                            'Hold a valid certificate of sponsorship and meet salary rules.',
                            'Meet the English language requirement and route-specific professional conditions.',
                            'Provide passport and any additional documents such as criminal record evidence where required.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Graduate',
                        'subclass' => 'Graduate',
                        'summary' => 'Post-study route for eligible graduates completing a qualifying UK course.',
                        'url' => 'https://www.gov.uk/graduate-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'new_application',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Have successfully completed an eligible UK course.',
                            'Apply from inside the UK while holding qualifying student permission.',
                            'Meet any timing and sponsorship history conditions for the route.',
                            'Provide passport and identity evidence through the UKVI process.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Global Talent',
                        'subclass' => 'Global Talent',
                        'summary' => 'Route for leaders or potential leaders in academia, research, arts, culture, or digital technology.',
                        'url' => 'https://www.gov.uk/global-talent',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 60,
                        'stay_duration_days' => 1825,
                        'dependants_allowed' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Obtain endorsement or qualify for an endorsed-exemption pathway where applicable.',
                            'Show achievement or potential in an eligible field.',
                            'Provide identity and endorsement-related evidence required by the route.',
                            'Apply through the UKVI process with the correct field and endorsement basis.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Innovator Founder',
                        'subclass' => 'Innovator Founder',
                        'summary' => 'Business route for founders developing an innovative, viable, and scalable business in the UK.',
                        'url' => 'https://www.gov.uk/innovator-founder-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 36,
                        'stay_duration_days' => 1095,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Obtain endorsement for an innovative, viable, and scalable business idea.',
                            'Meet the English language and financial requirements.',
                            'Provide business, endorsement, and identity documents required by UKVI.',
                            'Be prepared to continue meeting endorsement conditions after grant.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Scale-up Worker',
                        'subclass' => 'Scale-up Worker',
                        'summary' => 'Work route for eligible applicants sponsored by a qualifying UK scale-up business.',
                        'url' => 'https://www.gov.uk/scale-up-worker-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Have an eligible job offer from a qualifying UK scale-up sponsor.',
                            'Hold a valid certificate of sponsorship where the route requires sponsorship at entry.',
                            'Meet salary and English language requirements.',
                            'Provide passport and supporting documents through the UKVI process.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Creative Worker',
                        'subclass' => 'Temporary Work - Creative Worker',
                        'summary' => 'Temporary work route for eligible creative sector roles in the UK.',
                        'url' => 'https://www.gov.uk/creative-worker-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 12,
                        'stay_duration_days' => 365,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Have a qualifying creative sector sponsor and certificate of sponsorship.',
                            'Show the role fits the Creative Worker route rules.',
                            'Meet the financial requirement unless exempt.',
                            'Provide passport and route-specific supporting evidence through UKVI.',
                        ],
                    ]),
                    $this->makeVisa('UK', [
                        'name' => 'Family',
                        'subclass' => 'Family',
                        'summary' => 'Family route for joining or staying with an eligible partner, parent, or child in the UK.',
                        'url' => 'https://www.gov.uk/uk-family-visa',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 30,
                        'stay_duration_days' => 912,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'biometrics_required' => true,
                        'requirements' => [
                            'Show an eligible family relationship to a sponsor in the UK.',
                            'Meet the route’s relationship, suitability, and financial requirements.',
                            'Provide identity documents and evidence of the qualifying relationship.',
                            'Follow the correct application path depending on where the applicant is applying from.',
                        ],
                    ]),
                ],
            ],
            'united-states' => [
                'country' => 'United States',
                'prefix' => 'US',
                'reference_note' => 'Seeded from the U.S. Department of State visa directory and official U.S. visa guidance.',
                'visas' => [
                    $this->makeVisa('US', [
                        'name' => 'Visitor',
                        'subclass' => 'B-1 / B-2',
                        'summary' => 'Nonimmigrant visitor visa for temporary business or tourism travel to the United States.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/all-visa-categories.html',
                        'entry_type' => 'multiple_entry',
                        'stay_duration_days' => 180,
                        'financial_proof_required' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Show the visit is temporary and for business visitor or tourism purposes.',
                            'Demonstrate strong ties outside the United States and intent to depart after the visit.',
                            'Provide passport, DS-160, and supporting documents requested by the consular post.',
                            'Show ability to pay for the trip and stay without unauthorized employment.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Student',
                        'subclass' => 'F-1',
                        'summary' => 'Nonimmigrant student visa for full-time academic study at a U.S. school or program.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 60,
                        'stay_duration_days' => 1825,
                        'financial_proof_required' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Obtain Form I-20 from a SEVP-certified school.',
                            'Pay SEVIS and complete the DS-160 or required consular forms.',
                            'Show financial ability to pay for study and living costs.',
                            'Demonstrate nonimmigrant intent and qualification for the chosen program.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Exchange Visitor',
                        'subclass' => 'J-1',
                        'summary' => 'Nonimmigrant exchange visitor visa for approved cultural, educational, or professional exchange programs.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/study/exchange.html',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'interview_required' => true,
                        'requirements' => [
                            'Obtain Form DS-2019 from an approved exchange program sponsor.',
                            'Pay SEVIS if required and complete the consular application steps.',
                            'Show eligibility for the specific exchange category and program purpose.',
                            'Provide passport and supporting documents requested by the consular post.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Vocational Student',
                        'subclass' => 'M-1',
                        'summary' => 'Nonimmigrant student visa for vocational or other nonacademic study in the United States.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 24,
                        'stay_duration_days' => 730,
                        'financial_proof_required' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Obtain the proper school document for the vocational programme.',
                            'Pay SEVIS if required and complete the visa application steps.',
                            'Show financial ability to cover the course and living expenses.',
                            'Demonstrate qualification for the programme and nonimmigrant intent.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Specialty Occupation Worker',
                        'subclass' => 'H-1B',
                        'summary' => 'Nonimmigrant work visa for specialty occupations supported by an approved U.S. petition.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/employment/temporary-worker-visas.html',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 36,
                        'stay_duration_days' => 1095,
                        'dependants_allowed' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Have an approved petition or petition-based work case from the U.S. employer.',
                            'Show the position qualifies as a specialty occupation and the applicant is qualified.',
                            'Provide the petition, passport, DS-160, and supporting documents requested by the consular post.',
                            'Attend interview and administrative processing steps as required.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Intracompany Transferee',
                        'subclass' => 'L-1',
                        'summary' => 'Nonimmigrant work visa for executives, managers, or specialized knowledge employees transferred within a company group.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/employment/temporary-worker-visas.html',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 36,
                        'stay_duration_days' => 1095,
                        'dependants_allowed' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Have a qualifying company relationship and an approved transfer case where required.',
                            'Show the applicant meets the executive, managerial, or specialized knowledge role criteria.',
                            'Provide passport, petition evidence, and consular application documents.',
                            'Complete interview and any post-specific administrative processing steps.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Extraordinary Ability',
                        'subclass' => 'O-1',
                        'summary' => 'Nonimmigrant work visa for individuals with extraordinary ability or achievement.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/employment/temporary-worker-visas.html',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 36,
                        'stay_duration_days' => 1095,
                        'dependants_allowed' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Have a qualifying U.S. petitioner or sponsor and approved case where required.',
                            'Show extraordinary ability or achievement under the relevant O classification standard.',
                            'Provide petition evidence, passport, and consular application forms.',
                            'Complete consular interview and document review steps.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Treaty Investor',
                        'subclass' => 'E-2',
                        'summary' => 'Nonimmigrant visa for treaty investors directing and developing a qualifying U.S. investment enterprise.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/employment/treaty-trader-investor-visa-e.html',
                        'entry_type' => 'multiple_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 60,
                        'stay_duration_days' => 1825,
                        'dependants_allowed' => true,
                        'financial_proof_required' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Be a national of a treaty country and make a qualifying investment in a U.S. enterprise.',
                            'Show the enterprise is real and operating and the investment is substantial under the route.',
                            'Provide business, ownership, source of funds, and role documentation.',
                            'Complete DS-160 or post-specific E visa steps and interview requirements.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Fiancé(e)',
                        'subclass' => 'K-1',
                        'summary' => 'Nonimmigrant visa for a fiancé or fiancée of a U.S. citizen coming to marry in the United States.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/immigrate/family-immigration/fiancee-visa.html',
                        'entry_type' => 'single_entry',
                        'service_scope' => 'multi_step_case',
                        'stay_duration_days' => 90,
                        'medical_required' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Have a qualifying K petition filed by a U.S. citizen petitioner.',
                            'Show the relationship is genuine and the couple intends to marry within the allowed period after entry.',
                            'Complete medical, civil, and consular document requirements.',
                            'Attend the immigrant-visa-style interview process required for K visas.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Spouse Immigrant',
                        'subclass' => 'CR1 / IR1',
                        'summary' => 'Immigrant visa for the spouse of a U.S. citizen under conditional or immediate relative classification.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/immigrate/family-immigration.html',
                        'entry_type' => 'single_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 6,
                        'stay_duration_days' => 180,
                        'medical_required' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Have an approved immigrant petition and NVC or consular case ready for interview.',
                            'Provide civil documents, relationship evidence, and financial sponsorship documents.',
                            'Complete the immigrant visa application and medical examination steps.',
                            'Attend the immigrant visa interview at the designated U.S. consular post.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Employment-Based Immigrant',
                        'subclass' => 'EB-1 / EB-2 / EB-3',
                        'summary' => 'Immigrant pathways for qualifying employment-based applicants and sponsored workers.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/immigrate/employment-based-immigrant-visas.html',
                        'entry_type' => 'single_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 6,
                        'stay_duration_days' => 180,
                        'medical_required' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Have a qualifying employment-based petition or self-petition pathway where allowed.',
                            'Meet the category-specific criteria for the selected preference class.',
                            'Provide civil documents, petition records, and financial or employer evidence as required.',
                            'Complete the immigrant visa application, medical exam, and interview process.',
                        ],
                    ]),
                    $this->makeVisa('US', [
                        'name' => 'Diversity Visa',
                        'subclass' => 'DV',
                        'summary' => 'Immigrant visa issued through the U.S. Diversity Visa Program for selectees meeting statutory requirements.',
                        'url' => 'https://travel.state.gov/content/travel/en/us-visas/immigrate/diversity-visa-program-entry.html',
                        'entry_type' => 'single_entry',
                        'service_scope' => 'multi_step_case',
                        'validity_months' => 6,
                        'stay_duration_days' => 180,
                        'medical_required' => true,
                        'interview_required' => true,
                        'requirements' => [
                            'Be selected in the Diversity Visa Program and remain eligible through case processing.',
                            'Meet education or work experience requirements and other statutory conditions.',
                            'Provide civil documents, DS-260, and medical exam results when scheduled.',
                            'Attend the immigrant visa interview before the fiscal year deadlines expire.',
                        ],
                    ]),
                ],
            ],
        ];
    }

    private function makeVisa(string $prefix, array $attributes): array
    {
        $subclass = $attributes['subclass'];

        return [
            'name' => $attributes['name'],
            'code' => $attributes['code'] ?? $prefix.'-'.$subclass,
            'slug' => $attributes['slug'] ?? str($attributes['name'].' '.$subclass)->lower()->replace(['(', ')', '/'], '')->replace('  ', ' ')->slug()->value(),
            'official_subclass' => $subclass,
            'official_reference_url' => $attributes['url'],
            'official_summary' => $attributes['summary'],
            'official_requirements' => $attributes['requirements'],
            'submission_sla_days' => $attributes['submission_sla_days'] ?? 14,
            'decision_sla_days' => $attributes['decision_sla_days'] ?? 90,
            'validity_months' => $attributes['validity_months'] ?? null,
            'stay_duration_days' => $attributes['stay_duration_days'] ?? null,
            'entry_type' => $attributes['entry_type'] ?? 'multiple_entry',
            'service_scope' => $attributes['service_scope'] ?? 'new_application',
            'priority_support' => $attributes['priority_support'] ?? true,
            'dependants_allowed' => $attributes['dependants_allowed'] ?? false,
            'biometrics_required' => $attributes['biometrics_required'] ?? false,
            'interview_required' => $attributes['interview_required'] ?? false,
            'medical_required' => $attributes['medical_required'] ?? false,
            'police_clearance_required' => $attributes['police_clearance_required'] ?? false,
            'financial_proof_required' => $attributes['financial_proof_required'] ?? false,
            'checklist_intro' => $attributes['checklist_intro'] ?? 'Start from the official government page for the route, then confirm the applicant’s nationality, purpose, and stream before requesting documents.',
            'portal_guidance' => $attributes['portal_guidance'] ?? 'This seeded checklist is a practical starting point only. Final required documents can vary by embassy, stream, sponsor, and applicant history.',
            'notes' => $attributes['notes'] ?? ($attributes['reference_note'] ?? null),
        ];
    }
}
