<?php

namespace Database\Seeders;

use App\Actions\ProvisionVisaTypeDefaultsAction;
use App\Models\TargetCountry;
use App\Models\VisaType;
use Illuminate\Database\Seeder;

class AustralianVisaCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $australia = TargetCountry::query()->updateOrCreate(
            ['slug' => 'australia'],
            ['name' => 'Australia', 'is_active' => true],
        );

        $provisionDefaults = app(ProvisionVisaTypeDefaultsAction::class);

        foreach ($this->visaCatalog() as $visa) {
            $visaType = VisaType::query()->updateOrCreate(
                [
                    'target_country_id' => $australia->id,
                    'slug' => $visa['slug'],
                ],
                [
                    'name' => $visa['name'],
                    'code' => $visa['code'],
                    'official_subclass' => $visa['official_subclass'],
                    'is_active' => true,
                    'submission_sla_days' => $visa['submission_sla_days'],
                    'decision_sla_days' => $visa['decision_sla_days'],
                    'validity_months' => $visa['validity_months'],
                    'stay_duration_days' => $visa['stay_duration_days'],
                    'entry_type' => $visa['entry_type'],
                    'service_scope' => $visa['service_scope'],
                    'priority_support' => $visa['priority_support'],
                    'dependants_allowed' => $visa['dependants_allowed'],
                    'biometrics_required' => $visa['biometrics_required'],
                    'interview_required' => $visa['interview_required'],
                    'medical_required' => $visa['medical_required'],
                    'police_clearance_required' => $visa['police_clearance_required'],
                    'financial_proof_required' => $visa['financial_proof_required'],
                    'checklist_intro' => $visa['checklist_intro'],
                    'portal_guidance' => $visa['portal_guidance'],
                    'notes' => $visa['notes'],
                    'official_reference_url' => $visa['official_reference_url'],
                    'official_summary' => $visa['official_summary'],
                    'official_requirements' => $visa['official_requirements'],
                ],
            );

            $provisionDefaults->execute($visaType);
        }
    }

    private function visaCatalog(): array
    {
        return [
            $this->makeVisa([
                'name' => 'Visitor',
                'subclass' => '600',
                'summary' => 'Short stay visitor visa for tourism, family visits, or limited business visitor activity.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600',
                'entry_type' => 'multiple_entry',
                'validity_months' => 12,
                'stay_duration_days' => 90,
                'financial_proof_required' => true,
                'requirements' => [
                    'Hold a valid passport and identity documents.',
                    'Show a genuine temporary stay purpose such as tourism, family visit, or eligible business visitor activity.',
                    'Demonstrate enough funds for the stay and onward or return travel.',
                    'Meet health and character requirements if requested by Home Affairs.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Electronic Travel Authority',
                'subclass' => '601',
                'summary' => 'Electronic visitor visa for eligible passport holders travelling for tourism or short business visits.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/electronic-travel-authority-601',
                'entry_type' => 'multiple_entry',
                'validity_months' => 12,
                'stay_duration_days' => 90,
                'requirements' => [
                    'Be an eligible passport holder and apply through an approved channel.',
                    'Travel only for tourism or short business visitor activity.',
                    'Hold a valid passport linked to the ETA application.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'eVisitor',
                'subclass' => '651',
                'summary' => 'Online visitor visa for eligible European passport holders travelling for tourism or business visitor purposes.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651',
                'entry_type' => 'multiple_entry',
                'validity_months' => 12,
                'stay_duration_days' => 90,
                'requirements' => [
                    'Hold a passport from an eligible country.',
                    'Travel only for tourism or permitted business visitor activity.',
                    'Stay within the temporary stay conditions for each visit.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Transit',
                'subclass' => '771',
                'summary' => 'Short transit visa for travellers passing through Australia, usually for up to 72 hours.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/transit-771',
                'entry_type' => 'single_entry',
                'stay_duration_days' => 3,
                'priority_support' => false,
                'requirements' => [
                    'Show confirmed onward travel from Australia within the transit period.',
                    'Hold documents needed to enter the next destination.',
                    'Use the visa only for transit or limited related activity allowed by the subclass.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Medical Treatment',
                'subclass' => '602',
                'summary' => 'Temporary visa for people coming to Australia for medical treatment or to support someone receiving treatment.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/medical-treatment-602',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'stay_duration_days' => 180,
                'medical_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Provide evidence of the medical treatment, consultation, or support purpose.',
                    'Show arrangements for treatment, accommodation, and living costs in Australia.',
                    'Hold a valid passport and any supporting medical documents.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Working Holiday',
                'subclass' => '417',
                'summary' => 'Temporary visa for eligible young adults to holiday in Australia and work incidentally.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/working-holiday-417',
                'entry_type' => 'multiple_entry',
                'validity_months' => 12,
                'stay_duration_days' => 365,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be within the eligible age range and hold a passport from an eligible country.',
                    'Show enough funds to support the initial stay and onward travel.',
                    'Apply for the correct Working Holiday stream, including repeat applications if relevant.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Temporary Work (Short Stay Specialist)',
                'subclass' => '400',
                'summary' => 'Short-term temporary work visa for highly specialised, non-ongoing work in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-short-stay-specialist-400',
                'entry_type' => 'single_entry',
                'stay_duration_days' => 90,
                'financial_proof_required' => true,
                'requirements' => [
                    'Show the work is short term, highly specialised, and non-ongoing.',
                    'Provide evidence of the assignment, specialist background, and Australian engagement.',
                    'Demonstrate the applicant has the skills and experience to perform the work.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Temporary Work (International Relations)',
                'subclass' => '403',
                'summary' => 'Temporary visa for people working in Australia under government agreements or specific international relations arrangements.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-international-relations-403',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 24,
                'stay_duration_days' => 730,
                'requirements' => [
                    'Apply in the correct stream linked to a government agreement, foreign government agency, domestic worker arrangement, or privileges and immunities framework.',
                    'Provide stream-specific support or endorsement documents.',
                    'Show the proposed work matches the permitted activity for the selected stream.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Temporary Activity',
                'subclass' => '408',
                'summary' => 'Temporary visa for a range of short-term endorsed activities, events, and special program streams.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-activity-408',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 24,
                'stay_duration_days' => 730,
                'requirements' => [
                    'Choose the correct activity stream and provide any sponsorship, endorsement, or invitation required for that stream.',
                    'Show the proposed activity in Australia matches the permitted stream conditions.',
                    'Provide identity, itinerary, and supporting event or organisation documents.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Work and Holiday',
                'subclass' => '462',
                'summary' => 'Temporary visa for eligible young adults from specified countries to holiday and work in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-and-holiday-462',
                'entry_type' => 'multiple_entry',
                'validity_months' => 12,
                'stay_duration_days' => 365,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be within the eligible age range and hold a passport from an eligible country.',
                    'Meet any country-specific education or government support letter requirements.',
                    'Show enough funds for the initial stay and onward travel.',
                    'Meet health and character requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Special Category',
                'subclass' => '444',
                'summary' => 'Temporary visa for eligible New Zealand citizens, usually granted on arrival subject to immigration checks.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/special-category-444',
                'entry_type' => 'multiple_entry',
                'priority_support' => false,
                'requirements' => [
                    'Be a New Zealand citizen entering Australia with a valid New Zealand passport.',
                    'Satisfy character and other entry requirements checked at the border.',
                    'Not fall within exclusion categories that prevent grant of the visa.',
                    'Comply with any conditions or status limitations attached to the subclass.',
                ],
                'notes' => 'Usually granted automatically to eligible New Zealand citizens on arrival rather than through a standard lodged application.',
            ]),
            $this->makeVisa([
                'name' => 'New Zealand Citizen Family Relationship',
                'subclass' => '461',
                'summary' => 'Temporary visa for non-New Zealand family members of eligible New Zealand citizens living in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/new-zealand-citizen-family-relationship-461',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'requirements' => [
                    'Be a non-New Zealand family member of an eligible New Zealand citizen.',
                    'Show the qualifying family relationship and evidence the New Zealand citizen is usually resident in Australia.',
                    'Provide identity and relationship evidence for all included family members.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Student',
                'subclass' => '500',
                'summary' => 'Student visa for full-time study in a registered Australian course.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 365,
                'dependants_allowed' => true,
                'medical_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Provide confirmation of enrolment in a registered Australian course.',
                    'Meet the genuine student requirement and explain the study plan.',
                    'Show financial capacity for tuition, living costs, and travel.',
                    'Hold Overseas Student Health Cover and meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Student Guardian',
                'subclass' => '590',
                'summary' => 'Guardian visa for a parent or eligible relative supporting an international student in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-guardian-590',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 365,
                'medical_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be the parent, custodian, or eligible relative of the student visa holder.',
                    'Show welfare arrangements for the student in Australia.',
                    'Demonstrate financial capacity for living costs and travel.',
                    'Meet health insurance, health, and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Training',
                'subclass' => '407',
                'summary' => 'Temporary visa for structured workplace-based training to improve skills or support professional development.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/training-407',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 24,
                'stay_duration_days' => 730,
                'dependants_allowed' => true,
                'medical_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be sponsored and nominated for an approved occupational training program.',
                    'Show the training is structured and directly linked to skills development.',
                    'Provide evidence of recent study or work experience if required for the training stream.',
                    'Meet health, character, and financial support requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Temporary Graduate',
                'subclass' => '485',
                'summary' => 'Temporary post-study visa for eligible recent Australian graduates.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-graduate-485',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'new_application',
                'validity_months' => 36,
                'stay_duration_days' => 1095,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Hold an eligible recent Australian qualification and apply within the required timeframe.',
                    'Meet the stream-specific criteria for the Graduate Work or Post-Vocational Education Work stream in force at lodgement.',
                    'Provide evidence of English, health insurance, and identity documents.',
                    'Meet health and character requirements, including police checks where required.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Skilled Recognised Graduate',
                'subclass' => '476',
                'summary' => 'Temporary visa for recent engineering graduates from specified institutions.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-recognised-graduate-476',
                'entry_type' => 'multiple_entry',
                'validity_months' => 18,
                'stay_duration_days' => 540,
                'financial_proof_required' => true,
                'requirements' => [
                    'Have an engineering qualification from a specified institution within the permitted timeframe.',
                    'Be under the age limit that applies at the time of application.',
                    'Provide evidence of English language ability and identity documents.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Former Resident',
                'subclass' => '151',
                'summary' => 'Permanent return pathway for former Australian permanent residents or former citizen-related classes who meet the specific subclass criteria.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/former-resident-151',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'priority_support' => false,
                'requirements' => [
                    'Have held the qualifying former resident or related status required for subclass 151.',
                    'Show the applicant meets the specific former resident return criteria at lodgement.',
                    'Provide evidence of historical status, identity, and ties to Australia as required.',
                    'Meet character requirements and any health requirements if requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Resident Return',
                'subclass' => '155',
                'summary' => 'Resident return visa for current or former Australian permanent residents seeking a new travel facility.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/resident-return-155',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'renewal',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'priority_support' => false,
                'requirements' => [
                    'Be a current or former Australian permanent resident, or former Australian citizen, who meets the return resident rules.',
                    'Show the required period of residence in Australia or substantial ties of benefit to Australia.',
                    'Provide evidence of identity, immigration status history, and ties to Australia.',
                    'Meet character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Resident Return',
                'subclass' => '157',
                'summary' => 'Shorter resident return visa for people who do not meet the longer subclass 155 travel facility criteria.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/resident-return-157',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'renewal',
                'validity_months' => 3,
                'stay_duration_days' => 90,
                'priority_support' => false,
                'requirements' => [
                    'Be a current or former Australian permanent resident, or former Australian citizen, who meets the subclass 157 criteria.',
                    'Show a shorter recent residence period or compelling reasons for absence together with ties to Australia where relevant.',
                    'Provide evidence of identity, status history, and ties to Australia.',
                    'Meet character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Skills in Demand',
                'subclass' => '482',
                'summary' => 'Employer-sponsored temporary work visa for skilled workers nominated by an approved sponsor.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skills-in-demand-visa-subclass-482',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 48,
                'stay_duration_days' => 1460,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'financial_proof_required' => false,
                'requirements' => [
                    'Be nominated by an approved sponsoring employer for an eligible role or stream.',
                    'Meet the skills, work experience, and English criteria for the nominated stream.',
                    'Provide evidence of genuine employment and any required licences or registrations.',
                    'Meet health and character requirements, including police clearances where requested.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Employer Nomination Scheme',
                'subclass' => '186',
                'summary' => 'Permanent employer-sponsored skilled visa based on nomination by an Australian employer.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/employer-nomination-scheme-186',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Be nominated by an eligible Australian employer in the relevant stream.',
                    'Meet age, skills, qualifications, and English requirements unless exempt.',
                    'Provide any required skills assessment, work history, and licensing evidence.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Skilled Independent',
                'subclass' => '189',
                'summary' => 'Points-tested permanent skilled visa for invited applicants without employer or state sponsorship.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Submit an expression of interest and receive an invitation to apply.',
                    'Nominate an occupation on the relevant skilled occupation list and obtain a suitable skills assessment.',
                    'Meet the points test, age, and English requirements in force at invitation.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Skilled Nominated',
                'subclass' => '190',
                'summary' => 'Points-tested permanent skilled visa for invited applicants nominated by a state or territory.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Submit an expression of interest and receive state or territory nomination plus an invitation to apply.',
                    'Nominate an eligible occupation and obtain a suitable skills assessment.',
                    'Meet points test, age, English, and any state nomination requirements.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Skilled Work Regional (Provisional)',
                'subclass' => '491',
                'summary' => 'Points-tested provisional skilled visa for applicants nominated by a state or sponsored by eligible family in regional Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-work-regional-provisional-491',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Submit an expression of interest and receive an invitation based on state nomination or eligible family sponsorship.',
                    'Nominate an eligible occupation and obtain a suitable skills assessment.',
                    'Meet the points test, age, English, and regional criteria.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Skilled Employer Sponsored Regional (Provisional)',
                'subclass' => '494',
                'summary' => 'Regional employer-sponsored provisional skilled visa based on an approved nomination.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-employer-sponsored-regional-494',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Be nominated by an approved regional employer in an eligible occupation.',
                    'Meet age, skills, qualifications, work experience, and English requirements unless exempt.',
                    'Provide any required licensing, registration, or skills assessment evidence.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Permanent Residence (Skilled Regional)',
                'subclass' => '191',
                'summary' => 'Permanent visa for eligible holders of certain regional provisional skilled visas.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/permanent-residence-skilled-regional-191',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Hold an eligible regional provisional visa and satisfy the qualifying period requirements.',
                    'Provide evidence of taxable income and regional compliance where required.',
                    'Meet any continuing family member or dependent criteria if included.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Skilled Regional',
                'subclass' => '887',
                'summary' => 'Permanent visa for eligible holders of certain older regional skilled provisional visas.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-887',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Hold an eligible regional provisional skilled visa.',
                    'Meet the residence and work requirements for the relevant provisional pathway.',
                    'Provide evidence of regional residence and qualifying work history.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'National Innovation',
                'subclass' => '858',
                'summary' => 'Permanent visa for exceptionally talented individuals with an internationally recognised record of achievement.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/national-innovation-visa-858',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Show an internationally recognised record of exceptional achievement in an eligible field.',
                    'Provide nomination by an eligible Australian nominator where required by the current program settings.',
                    'Demonstrate the ability to contribute to Australia in the field of achievement.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Business Innovation and Investment (Provisional)',
                'subclass' => '188',
                'summary' => 'Provisional business or investor pathway for applicants nominated by a state, territory, or Austrade where applicable.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-provisional-188',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be invited to apply in the relevant stream and hold required nomination where applicable.',
                    'Meet stream-specific business, investment, innovation, or net asset requirements.',
                    'Provide evidence of business history, lawful funds, and source of assets if required.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Business Innovation and Investment (Permanent)',
                'subclass' => '888',
                'summary' => 'Permanent follow-on visa for eligible provisional business or investor visa holders.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-888',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Hold an eligible provisional business or investor visa and continue to meet the stream criteria.',
                    'Provide evidence of business operations, investment activity, or innovation outcomes in Australia.',
                    'Maintain the required state, territory, or Austrade nomination where relevant.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Prospective Marriage',
                'subclass' => '300',
                'summary' => 'Temporary visa for a fiancé or fiancée of an Australian citizen, permanent resident, or eligible New Zealand citizen.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/prospective-marriage-300',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 15,
                'stay_duration_days' => 270,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Be sponsored by an eligible Australian partner and intend to marry after grant.',
                    'Show the relationship is genuine and both parties have met in person as required.',
                    'Provide identity, relationship, and sponsor documents.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Partner (Provisional)',
                'subclass' => '309',
                'summary' => 'Offshore temporary partner visa for spouses or de facto partners of eligible Australian sponsors.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-provisional-309',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 24,
                'stay_duration_days' => 730,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Apply outside Australia and be sponsored by an eligible Australian partner.',
                    'Show the marriage or de facto relationship is genuine and continuing.',
                    'Provide relationship history, shared life evidence, and sponsor documents.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Partner (Migrant)',
                'subclass' => '100',
                'summary' => 'Permanent offshore partner visa usually following subclass 309 assessment.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-migrant-100',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Usually hold or have held the relevant provisional partner pathway status.',
                    'Continue to meet the genuine and continuing relationship requirement.',
                    'Provide updated relationship and sponsor evidence when requested.',
                    'Meet health and character requirements if further checks are needed.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Partner (Temporary)',
                'subclass' => '820',
                'summary' => 'Onshore temporary partner visa for spouses or de facto partners of eligible Australian sponsors.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-820',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 24,
                'stay_duration_days' => 730,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Apply while in Australia and be sponsored by an eligible Australian partner.',
                    'Show the marriage or de facto relationship is genuine and continuing.',
                    'Provide relationship history, shared life evidence, and sponsor documents.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Partner',
                'subclass' => '801',
                'summary' => 'Permanent onshore partner visa usually following subclass 820 assessment.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-801',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => true,
                'medical_required' => true,
                'police_clearance_required' => true,
                'requirements' => [
                    'Usually hold or have held the relevant temporary partner pathway status.',
                    'Continue to meet the genuine and continuing relationship requirement.',
                    'Provide updated relationship and sponsor evidence when requested.',
                    'Meet health and character requirements if further checks are needed.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Parent',
                'subclass' => '103',
                'summary' => 'Permanent parent visa for eligible parents of settled Australian children, subject to capping and queueing.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/parent-103',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'dependants_allowed' => false,
                'medical_required' => true,
                'police_clearance_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be the parent of a settled Australian citizen, permanent resident, or eligible New Zealand citizen child.',
                    'Pass the balance of family test unless exempt under the law.',
                    'Meet the assurance of support and any queueing or capping requirements.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Contributory Parent',
                'subclass' => '143',
                'summary' => 'Permanent parent visa with higher application costs but generally shorter queueing than subclass 103.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-parent-143',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'police_clearance_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be the parent of a settled Australian child and pass the balance of family test.',
                    'Meet the assurance of support requirements and pay the contributory charges.',
                    'Provide family composition and sponsor eligibility evidence.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Contributory Parent (Temporary)',
                'subclass' => '173',
                'summary' => 'Temporary contributory parent pathway that can lead to subclass 143.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-parent-temporary-173',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 24,
                'stay_duration_days' => 730,
                'medical_required' => true,
                'police_clearance_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be the parent of a settled Australian child and pass the balance of family test.',
                    'Meet the assurance of support requirements and contributory temporary pathway criteria.',
                    'Provide family composition and sponsor eligibility evidence.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Sponsored Parent (Temporary)',
                'subclass' => '870',
                'summary' => 'Temporary parent visa requiring sponsorship by an approved child in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/sponsored-parent-temporary-870',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 36,
                'stay_duration_days' => 1095,
                'financial_proof_required' => true,
                'requirements' => [
                    'Have an approved parent sponsor before lodging the visa application.',
                    'Be the biological, adoptive, or step parent of the approved sponsor.',
                    'Maintain adequate health insurance and meet financial support expectations.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Aged Parent',
                'subclass' => '804',
                'summary' => 'Onshore permanent parent visa for eligible older parents, subject to capping and queueing.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/aged-parent-804',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'police_clearance_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be old enough to receive the Australian age pension and be in Australia when applying.',
                    'Pass the balance of family test unless exempt under the law.',
                    'Meet assurance of support and queueing requirements.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Contributory Aged Parent',
                'subclass' => '864',
                'summary' => 'Onshore permanent contributory parent visa for eligible older parents.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-aged-parent-864',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'police_clearance_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be old enough to receive the Australian age pension and be in Australia when applying.',
                    'Pass the balance of family test unless exempt under the law.',
                    'Meet assurance of support requirements and pay the contributory charges.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Contributory Aged Parent (Temporary)',
                'subclass' => '884',
                'summary' => 'Temporary onshore contributory parent pathway that can lead to subclass 864.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-aged-parent-temporary-884',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 24,
                'stay_duration_days' => 730,
                'medical_required' => true,
                'police_clearance_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be old enough to receive the Australian age pension and be in Australia when applying.',
                    'Pass the balance of family test unless exempt under the law.',
                    'Meet assurance of support requirements and temporary contributory parent criteria.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Aged Dependent Relative',
                'subclass' => '114',
                'summary' => 'Offshore permanent family visa for older dependent relatives of eligible Australian sponsors.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/aged-dependent-relative-114',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Apply outside Australia and be sponsored by an eligible relative in Australia.',
                    'Be old enough to qualify as aged and be dependent on the sponsor or sponsor’s partner.',
                    'Show there is no near relative able to provide support outside Australia where required by the subclass.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Remaining Relative',
                'subclass' => '115',
                'summary' => 'Offshore permanent family visa for applicants whose only near relatives live in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/remaining-relative-115',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Apply outside Australia and be sponsored by an eligible Australian relative.',
                    'Show the applicant’s only near relatives usually live in Australia and are eligible relatives under the law.',
                    'Provide family composition, identity, and sponsor evidence.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Carer',
                'subclass' => '116',
                'summary' => 'Offshore permanent family visa for applicants who will move to Australia to provide long-term care to a relative.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/carer-116',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Apply outside Australia and be sponsored by an eligible Australian relative or their family member.',
                    'Provide a medical assessment showing the Australian relative needs long-term care.',
                    'Show the care cannot reasonably be obtained from other sources in Australia.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Child',
                'subclass' => '101',
                'summary' => 'Offshore permanent child visa for eligible children of Australian citizens, permanent residents, or eligible New Zealand citizens.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/child-101',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Apply outside Australia and be sponsored by an eligible parent or parent’s partner where allowed.',
                    'Show the child meets the age, dependency, or disability criteria for the subclass.',
                    'Provide custody, consent, and identity evidence where relevant.',
                    'Meet health and character requirements if applicable.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Adoption',
                'subclass' => '102',
                'summary' => 'Offshore visa for a child adopted or to be adopted through approved intercountry processes.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/adoption-102',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Be sponsored by an eligible adoptive parent in Australia.',
                    'Provide approved adoption or proposed adoption documents that meet Australian requirements.',
                    'Provide custody, identity, and child welfare evidence.',
                    'Meet health and character requirements if applicable.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Child',
                'subclass' => '802',
                'summary' => 'Onshore permanent child visa for eligible children of Australian citizens, permanent residents, or eligible New Zealand citizens.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/child-802',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Be in Australia at application and decision if required by the subclass rules.',
                    'Show the child meets the age, dependency, or disability criteria for the subclass.',
                    'Provide custody, consent, and identity evidence where relevant.',
                    'Meet health and character requirements if applicable.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Dependent Child',
                'subclass' => '445',
                'summary' => 'Temporary visa for a dependent child of a parent holding or applying for a temporary partner visa.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/dependent-child-445',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 24,
                'stay_duration_days' => 730,
                'medical_required' => true,
                'requirements' => [
                    'Be the dependent child of a parent connected to an eligible partner visa pathway.',
                    'Show the child meets age, dependency, and custody requirements.',
                    'Provide identity and relationship evidence linking the child to the principal applicant.',
                    'Meet health and character requirements if applicable.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Orphan Relative',
                'subclass' => '117',
                'summary' => 'Offshore permanent family visa for certain orphaned relatives sponsored by eligible family in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/orphan-relative-117',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Apply outside Australia and be sponsored by an eligible relative in Australia.',
                    'Show the child is orphaned, cannot be cared for by parents, or otherwise meets the orphan relative criteria.',
                    'Provide custody, consent, identity, and welfare evidence.',
                    'Meet health and character requirements if applicable.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Remaining Relative',
                'subclass' => '835',
                'summary' => 'Onshore permanent family visa for applicants whose only near relatives live in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/remaining-relative-835',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Be in Australia and be sponsored by an eligible Australian relative.',
                    'Show the applicant’s only near relatives usually live in Australia and are eligible relatives under the law.',
                    'Provide family composition, identity, and sponsor evidence.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Carer',
                'subclass' => '836',
                'summary' => 'Onshore permanent family visa for applicants who will remain in Australia to provide long-term care to a relative.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/carer-836',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Be in Australia and be sponsored by an eligible Australian relative or their family member.',
                    'Provide a medical assessment showing the Australian relative needs long-term care.',
                    'Show the care cannot reasonably be obtained from other sources in Australia.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Orphan Relative',
                'subclass' => '837',
                'summary' => 'Onshore permanent family visa for certain orphaned relatives sponsored by eligible family in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/orphan-relative-837',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'requirements' => [
                    'Be in Australia and be sponsored by an eligible relative in Australia.',
                    'Show the child is orphaned, cannot be cared for by parents, or otherwise meets the orphan relative criteria.',
                    'Provide custody, consent, identity, and welfare evidence.',
                    'Meet health and character requirements if applicable.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Aged Dependent Relative',
                'subclass' => '838',
                'summary' => 'Onshore permanent family visa for older dependent relatives of eligible Australian sponsors.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/aged-dependent-relative-838',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'validity_months' => 60,
                'stay_duration_days' => 1825,
                'medical_required' => true,
                'financial_proof_required' => true,
                'requirements' => [
                    'Be in Australia and be sponsored by an eligible relative in Australia.',
                    'Be old enough to qualify as aged and be dependent on the sponsor or sponsor’s partner.',
                    'Show there is no near relative able to provide support outside Australia where required by the subclass.',
                    'Meet health and character requirements.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Protection',
                'subclass' => '866',
                'summary' => 'Protection visa for people in Australia who engage Australia’s protection obligations.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/protection-866',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'police_clearance_required' => false,
                'requirements' => [
                    'Be in Australia and engage Australia’s protection obligations under the migration framework.',
                    'Provide a detailed protection claim with supporting identity and country information.',
                    'Meet any application validity and bar-related requirements in force at lodgement.',
                    'Cooperate with health, security, and identity checks.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Temporary Protection',
                'subclass' => '785',
                'summary' => 'Temporary protection visa for certain protection applicants who meet Australia’s protection obligations.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-protection-785',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Be in Australia and satisfy the pathway requirements that apply to temporary protection applicants.',
                    'Show Australia owes protection obligations based on the applicant’s circumstances.',
                    'Provide identity and protection claim evidence as fully as possible.',
                    'Cooperate with health, security, and identity checks.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Temporary (Humanitarian Concern)',
                'subclass' => '786',
                'summary' => 'Temporary humanitarian visa for certain protection applicants in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-humanitarian-concern-786',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Be in Australia and satisfy the pathway requirements for the humanitarian concern subclass.',
                    'Provide evidence supporting the humanitarian or protection-related claim.',
                    'Provide identity and background information as fully as possible.',
                    'Cooperate with health, security, and identity checks.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Safe Haven Enterprise',
                'subclass' => '790',
                'summary' => 'Temporary protection-related visa with regional work or study expectations for eligible applicants.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/safe-haven-enterprise-790',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Be in Australia and meet the pathway requirements for the SHEV subclass.',
                    'Show Australia owes protection obligations or otherwise meet the subclass criteria.',
                    'Understand the regional work or study pathway settings linked to the visa.',
                    'Cooperate with health, security, and identity checks.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Resolution of Status',
                'subclass' => '851',
                'summary' => 'Permanent visa for certain humanitarian or protection pathway holders under the resolution of status arrangements.',
                'url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/resolution-of-status-851',
                'entry_type' => 'multiple_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Hold or have held an eligible temporary protection-related visa and meet the resolution of status pathway rules.',
                    'Satisfy any residence, conduct, and pathway requirements that apply at application.',
                    'Provide identity and status history evidence as required.',
                    'Cooperate with health, security, and identity checks.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Refugee',
                'subclass' => '200',
                'summary' => 'Offshore refugee visa for people subject to substantial discrimination or human rights abuses in their home country.',
                'url' => 'https://immi.homeaffairs.gov.au/help-support/contact-us/offices-and-locations/lodging-an-application-ref-and-hum-visas',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Be outside Australia when applying for the offshore refugee program.',
                    'Meet the refugee criteria for subclass 200 under the program settings.',
                    'Provide identity and background information as fully as possible.',
                    'Cooperate with health and security checks.',
                ],
                'notes' => 'Home Affairs states a refugee and humanitarian application can cover subclasses 200, 201, 202, 203, and 204, with grant in the subclass whose criteria are met.',
            ]),
            $this->makeVisa([
                'name' => 'In-country Special Humanitarian',
                'subclass' => '201',
                'summary' => 'Offshore humanitarian visa for people subject to persecution in their home country who remain in that country.',
                'url' => 'https://immi.homeaffairs.gov.au/help-support/contact-us/offices-and-locations/lodging-an-application-ref-and-hum-visas',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Be outside Australia and remain in the home country when applying if required by the subclass rules.',
                    'Meet the humanitarian criteria for subclass 201.',
                    'Provide identity and protection-related information as fully as possible.',
                    'Cooperate with health and security checks.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Global Special Humanitarian',
                'subclass' => '202',
                'summary' => 'Offshore humanitarian visa for people outside their home country who face substantial discrimination and have a proposer in Australia.',
                'url' => 'https://immi.homeaffairs.gov.au/help-support/contact-us/offices-and-locations/lodging-an-application-ref-and-hum-visas',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Be outside the home country and outside Australia when applying.',
                    'Have an eligible proposer in Australia where the subclass requires one.',
                    'Show substantial discrimination or other humanitarian need under subclass 202 criteria.',
                    'Cooperate with identity, health, and security checks.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Emergency Rescue',
                'subclass' => '203',
                'summary' => 'Offshore humanitarian visa for people facing urgent resettlement needs identified under Australia’s humanitarian program.',
                'url' => 'https://immi.homeaffairs.gov.au/help-support/contact-us/offices-and-locations/lodging-an-application-ref-and-hum-visas',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Be outside Australia and fall within the urgent resettlement criteria for subclass 203.',
                    'Provide identity and case background information as fully as possible.',
                    'Be available for referral, assessment, and urgent travel arrangements where applicable.',
                    'Cooperate with health and security checks.',
                ],
            ]),
            $this->makeVisa([
                'name' => 'Woman at Risk',
                'subclass' => '204',
                'summary' => 'Offshore humanitarian visa for women facing danger, abuse, or serious vulnerability without male protection in the home country.',
                'url' => 'https://immi.homeaffairs.gov.au/help-support/contact-us/offices-and-locations/lodging-an-application-ref-and-hum-visas',
                'entry_type' => 'single_entry',
                'service_scope' => 'multi_step_case',
                'priority_support' => false,
                'medical_required' => true,
                'requirements' => [
                    'Be outside Australia and meet the woman at risk vulnerability criteria.',
                    'Provide identity and humanitarian circumstances information as fully as possible.',
                    'Show the protection need and lack of adequate support or protection.',
                    'Cooperate with health and security checks.',
                ],
            ]),
        ];
    }

    private function makeVisa(array $attributes): array
    {
        $subclass = $attributes['subclass'];
        $slug = $attributes['slug'] ?? str($attributes['name'].' '.$subclass)->lower()->replace(['(', ')', '/'], '')->replace('  ', ' ')->slug()->value();

        return [
            'name' => $attributes['name'],
            'code' => $attributes['code'] ?? 'AU-'.$subclass,
            'slug' => $slug,
            'official_subclass' => $subclass,
            'official_reference_url' => $attributes['url'],
            'official_summary' => $attributes['summary'],
            'official_requirements' => $attributes['requirements'],
            'submission_sla_days' => $attributes['submission_sla_days'] ?? 14,
            'decision_sla_days' => $attributes['decision_sla_days'] ?? 90,
            'validity_months' => $attributes['validity_months'] ?? null,
            'stay_duration_days' => $attributes['stay_duration_days'] ?? null,
            'entry_type' => $attributes['entry_type'] ?? 'multiple_entry',
            'service_scope' => $attributes['service_scope'] ?? 'new_application',
            'priority_support' => $attributes['priority_support'] ?? true,
            'dependants_allowed' => $attributes['dependants_allowed'] ?? false,
            'biometrics_required' => $attributes['biometrics_required'] ?? false,
            'interview_required' => $attributes['interview_required'] ?? false,
            'medical_required' => $attributes['medical_required'] ?? false,
            'police_clearance_required' => $attributes['police_clearance_required'] ?? false,
            'financial_proof_required' => $attributes['financial_proof_required'] ?? false,
            'checklist_intro' => $attributes['checklist_intro'] ?? 'Use the official subclass page to confirm current forms, identity documents, and stream-specific evidence before requesting uploads from the client.',
            'portal_guidance' => $attributes['portal_guidance'] ?? 'Requirements can change by stream, nationality, and personal history. Ask the client to upload clear copies first, then refine the checklist after a document review.',
            'notes' => $attributes['notes'] ?? 'Seeded from current Australian Government Home Affairs visa information. Reconfirm subclass criteria before filing.',
        ];
    }
}
