<?php

namespace Database\Seeders;

use App\Models\VisaRequirementTemplate;
use Illuminate\Database\Seeder;

class VisaRequirementTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $sourceCheckedAt = now()->toDateString();

        $templates = [
            [
                'region' => 'Australia',
                'country_name' => 'Australia',
                'visa_type' => 'Visitor visa',
                'visa_code' => '600',
                'label' => 'Australia visitor visa operational checklist',
                'description' => 'Short-stay visitor case prep for tourism, family visit, or business visitor streams.',
                'source_url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Processing varies by stream and applicant circumstances; verify current timing on the official portal.',
                'fee_summary' => null,
                'stay_summary' => 'Length of stay depends on stream and grant conditions.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Clear colour scan of current passport and any relevant prior visas.'],
                    ['category' => 'Application', 'label' => 'Completed visitor visa application', 'help_text' => 'Ensure names, travel dates, and passport details match supporting documents.'],
                    ['category' => 'Purpose', 'label' => 'Travel purpose statement', 'help_text' => 'Cover why the applicant is visiting and what they plan to do in Australia.'],
                    ['category' => 'Financial', 'label' => 'Proof of funds', 'help_text' => 'Bank statements, savings balances, or sponsor support evidence.'],
                    ['category' => 'Employment', 'label' => 'Employment or business evidence', 'help_text' => 'Job letter, leave approval, business registration, or self-employment proof.'],
                    ['category' => 'Travel', 'label' => 'Travel itinerary', 'help_text' => 'Planned flights, accommodation, and intended stay period.'],
                    ['category' => 'Sponsor', 'label' => 'Invitation or host details if applicable', 'help_text' => 'Include inviter identity, relationship, address, and support letter where relevant.'],
                    ['category' => 'Character', 'label' => 'Character and health history answers reviewed', 'help_text' => 'Flag any declarations that may require additional documents.'],
                ],
            ],
            [
                'region' => 'Australia',
                'country_name' => 'Australia',
                'visa_type' => 'Student visa',
                'visa_code' => '500',
                'label' => 'Australia student visa operational checklist',
                'description' => 'Education-focused intake with financial, enrolment, and Genuine Student evidence.',
                'source_url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Processing varies by education sector and applicant profile; verify on the official portal.',
                'fee_summary' => null,
                'stay_summary' => 'Stay length is linked to course dates and visa grant conditions.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use a readable colour scan and confirm passport validity covers study plans.'],
                    ['category' => 'Education', 'label' => 'Confirmation of enrolment', 'help_text' => 'COE or formal enrolment evidence from the education provider.'],
                    ['category' => 'Education', 'label' => 'Course and provider details reviewed', 'help_text' => 'Check provider, CRICOS details, intake date, and study level.'],
                    ['category' => 'Financial', 'label' => 'Financial capacity evidence', 'help_text' => 'Funds for tuition, living costs, and travel using acceptable evidence.'],
                    ['category' => 'English', 'label' => 'English language evidence', 'help_text' => 'IELTS, TOEFL, PTE, or exemption evidence where applicable.'],
                    ['category' => 'Statement', 'label' => 'Genuine Student statement draft', 'help_text' => 'Explain study intentions, background, and post-study rationale.'],
                    ['category' => 'Health', 'label' => 'Health insurance details', 'help_text' => 'OSHC policy details or provider arrangement for the study period.'],
                    ['category' => 'Background', 'label' => 'Academic and employment history bundle', 'help_text' => 'Transcripts, diplomas, CV, and employment evidence supporting the course choice.'],
                ],
            ],
            [
                'region' => 'Australia',
                'country_name' => 'Australia',
                'visa_type' => 'Skills in Demand visa',
                'visa_code' => '482',
                'label' => 'Australia skills in demand visa operational checklist',
                'description' => 'Employer-sponsored work pathway checklist, commonly aligned with subclass 482 processing.',
                'source_url' => 'https://immi.homeaffairs.gov.au/Visa-subsite/Pages/work/skills-in-demand-482-landing.aspx',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Review current subclass processing and nomination timing on the official Home Affairs portal.',
                'fee_summary' => null,
                'stay_summary' => 'Stay period depends on stream, nomination, and grant conditions.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Include current passport and relevant travel history if requested.'],
                    ['category' => 'Employment', 'label' => 'Resume or CV', 'help_text' => 'Show current role, duties, and employment chronology.'],
                    ['category' => 'Sponsorship', 'label' => 'Employer nomination or job offer details', 'help_text' => 'Collect sponsoring employer information and nominated occupation details.'],
                    ['category' => 'Employment', 'label' => 'Work experience evidence', 'help_text' => 'Reference letters, contracts, payslips, or tax evidence supporting claimed experience.'],
                    ['category' => 'Skills', 'label' => 'Skills assessment requirement reviewed', 'help_text' => 'Confirm whether the occupation requires a formal assessment.'],
                    ['category' => 'English', 'label' => 'English language evidence or exemption', 'help_text' => 'Capture test results or the applicable exemption basis.'],
                    ['category' => 'Health', 'label' => 'Health and character document plan', 'help_text' => 'Identify police certificates or medical checks that may be required.'],
                    ['category' => 'Dependants', 'label' => 'Dependant evidence if applicable', 'help_text' => 'Passport, relationship, and identity documents for accompanying family members.'],
                ],
            ],
            [
                'region' => 'Australia',
                'country_name' => 'Australia',
                'visa_type' => 'Working Holiday visa',
                'visa_code' => '417',
                'label' => 'Australia working holiday operational checklist',
                'description' => 'Checklist for short-term travel and work rights under the Working Holiday program.',
                'source_url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Confirm current processing and country eligibility on the official visa page.',
                'fee_summary' => null,
                'stay_summary' => 'Typically granted for temporary travel and work rights subject to program rules.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Confirm nationality and passport validity against program eligibility.'],
                    ['category' => 'Eligibility', 'label' => 'Country and age eligibility check', 'help_text' => 'Record nationality, age, and any ballot or quota conditions that apply.'],
                    ['category' => 'Financial', 'label' => 'Proof of sufficient funds', 'help_text' => 'Collect current financial evidence for arrival and initial support.'],
                    ['category' => 'Travel', 'label' => 'Return travel funds or onward ticket plan', 'help_text' => 'Document return ticket or funds to purchase onward travel.'],
                    ['category' => 'Application', 'label' => 'Recent passport-style photo if requested', 'help_text' => 'Keep digital image ready for online submission when needed.'],
                    ['category' => 'Health', 'label' => 'Health declarations reviewed', 'help_text' => 'Note any responses that may trigger medical follow-up.'],
                    ['category' => 'Character', 'label' => 'Character history answers reviewed', 'help_text' => 'Prepare supporting explanations if there are prior visa or legal issues.'],
                ],
            ],
            [
                'region' => 'Australia',
                'country_name' => 'Australia',
                'visa_type' => 'Partner visa',
                'visa_code' => '820',
                'label' => 'Australia partner visa operational checklist',
                'description' => 'Relationship evidence collection for applicants relying on spouse or de facto sponsorship.',
                'source_url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-onshore/temporary-820',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Partner processing can be lengthy and highly document-driven; review current timing on the official portal.',
                'fee_summary' => null,
                'stay_summary' => 'Pathway and stay conditions depend on visa stage and relationship circumstances.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Applicant and sponsor passports', 'help_text' => 'Use current passports and any relevant prior identity documents.'],
                    ['category' => 'Relationship', 'label' => 'Relationship timeline summary', 'help_text' => 'Chronology covering how the relationship started and developed.'],
                    ['category' => 'Financial', 'label' => 'Joint financial evidence', 'help_text' => 'Shared account activity, expenses, assets, or other financial interdependence.'],
                    ['category' => 'Household', 'label' => 'Cohabitation or household evidence', 'help_text' => 'Lease, bills, correspondence, or documents showing shared residence.'],
                    ['category' => 'Social', 'label' => 'Social relationship evidence', 'help_text' => 'Photos, travel, messages, and statements that show the relationship publicly.'],
                    ['category' => 'Civil status', 'label' => 'Civil status and identity documents', 'help_text' => 'Marriage certificate, divorce records, or household registration if relevant.'],
                    ['category' => 'Character', 'label' => 'Police clearance plan', 'help_text' => 'Identify which jurisdictions may require police certificates.'],
                ],
            ],
            [
                'region' => 'Australia',
                'country_name' => 'Australia',
                'visa_type' => 'Transit visa',
                'visa_code' => '771',
                'label' => 'Australia transit visa operational checklist',
                'description' => 'Short transit preparation for applicants passing through Australia to another destination.',
                'source_url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/transit-771',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check the official transit page for current processing and eligibility details.',
                'fee_summary' => null,
                'stay_summary' => 'Transit conditions are limited and tied to onward travel plans.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Confirm passport validity for transit and final destination.'],
                    ['category' => 'Travel', 'label' => 'Confirmed onward booking', 'help_text' => 'Ticket or itinerary showing departure from Australia.'],
                    ['category' => 'Travel', 'label' => 'Destination entry permission reviewed', 'help_text' => 'Check whether a visa or entry approval is needed for the next destination.'],
                    ['category' => 'Purpose', 'label' => 'Transit explanation note', 'help_text' => 'Short explanation of route and transit timing where useful.'],
                    ['category' => 'Documents', 'label' => 'Supporting destination visa copies if applicable', 'help_text' => 'Attach evidence for the onward destination where relevant.'],
                ],
            ],
            [
                'region' => 'Australia',
                'country_name' => 'Australia',
                'visa_type' => 'Training visa',
                'visa_code' => '407',
                'label' => 'Australia training visa operational checklist',
                'description' => 'Occupational training and professional development pathway checklist.',
                'source_url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/training-407',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Review sponsorship, nomination, and training plan requirements on the official page.',
                'fee_summary' => null,
                'stay_summary' => 'Temporary stay tied to the approved training activity and visa conditions.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Current passport and relevant travel history.'],
                    ['category' => 'Training', 'label' => 'Training plan or program outline', 'help_text' => 'Document the structured training content and duration.'],
                    ['category' => 'Sponsorship', 'label' => 'Sponsor and nomination details', 'help_text' => 'Capture sponsoring organisation and approved nomination details.'],
                    ['category' => 'Background', 'label' => 'Current role or study background evidence', 'help_text' => 'Show why the training is relevant to the applicant’s career path.'],
                    ['category' => 'Financial', 'label' => 'Financial support arrangement', 'help_text' => 'Confirm who covers living costs, travel, and any training expenses.'],
                    ['category' => 'Health', 'label' => 'Health and character review plan', 'help_text' => 'Identify additional checks that may be triggered.'],
                ],
            ],
            [
                'region' => 'Australia',
                'country_name' => 'Australia',
                'visa_type' => 'Temporary Graduate visa',
                'visa_code' => '485',
                'label' => 'Australia temporary graduate operational checklist',
                'description' => 'Post-study temporary stay checklist for eligible recent graduates.',
                'source_url' => 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-graduate-485',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check stream-specific timing and recent graduate eligibility on the official page.',
                'fee_summary' => null,
                'stay_summary' => 'Stay period depends on stream and current grant rules.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use the current passport and prior Australian visa history where relevant.'],
                    ['category' => 'Education', 'label' => 'Australian study completion evidence', 'help_text' => 'Completion letter, transcripts, and provider confirmation.'],
                    ['category' => 'Education', 'label' => 'Course and study requirement review', 'help_text' => 'Confirm the applicant meets the Australian study requirement for the chosen stream.'],
                    ['category' => 'English', 'label' => 'English evidence or exemption', 'help_text' => 'Collect test results or document the exemption basis.'],
                    ['category' => 'Health', 'label' => 'Health insurance and character plan', 'help_text' => 'Review OSHC/health cover status and police certificate needs.'],
                    ['category' => 'Timing', 'label' => 'Application timing eligibility confirmed', 'help_text' => 'Check filing window after course completion and current visa status.'],
                ],
            ],
            [
                'region' => 'Europe',
                'country_name' => 'Germany',
                'visa_type' => 'Short-stay Schengen visa',
                'visa_code' => 'C',
                'label' => 'Germany short-stay operational checklist',
                'description' => 'Operational checklist for short-stay Schengen travel, subject to nationality and local mission practice.',
                'source_url' => 'https://www.auswaertiges-amt.de/en/visa-service/231202-231202',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check the responsible mission and current Schengen processing guidance before filing.',
                'fee_summary' => null,
                'stay_summary' => 'Schengen stay is generally limited to 90 days within a 180-day period.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport and prior travel document copy', 'help_text' => 'Passport validity and available pages should satisfy Schengen rules.'],
                    ['category' => 'Application', 'label' => 'Completed Schengen application form', 'help_text' => 'Names, travel dates, and intended stay should match all bookings.'],
                    ['category' => 'Photo', 'label' => 'Recent biometric passport photos', 'help_text' => 'Use current photos that meet local mission specifications.'],
                    ['category' => 'Travel', 'label' => 'Flight reservation or travel plan', 'help_text' => 'Round-trip or onward travel plan covering the intended stay.'],
                    ['category' => 'Stay', 'label' => 'Accommodation evidence', 'help_text' => 'Hotel booking, host invitation, or other stay arrangement proof.'],
                    ['category' => 'Financial', 'label' => 'Financial means evidence', 'help_text' => 'Bank statements, sponsor support, or salary proof.'],
                    ['category' => 'Insurance', 'label' => 'Travel medical insurance', 'help_text' => 'Insurance should satisfy the destination mission’s Schengen requirements.'],
                    ['category' => 'Employment', 'label' => 'Home-country ties evidence', 'help_text' => 'Employment, study, business, or family evidence supporting return intent.'],
                ],
            ],
            [
                'region' => 'Europe',
                'country_name' => 'France',
                'visa_type' => 'Short-stay visa',
                'visa_code' => 'C',
                'label' => 'France short-stay operational checklist',
                'description' => 'Short-stay France filing checklist for tourism, business, transit, or family visit under France-Visas guidance.',
                'source_url' => 'https://france-visas.gouv.fr/en/web/france-visas/short-stay-visa',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check France-Visas and the local filing center for current timelines and document lists.',
                'fee_summary' => null,
                'stay_summary' => 'Short-stay travel is generally limited to 90 days within a 180-day period.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport and ID page copies', 'help_text' => 'Confirm passport validity and prior visa history where useful.'],
                    ['category' => 'Application', 'label' => 'France-Visas application completed', 'help_text' => 'Travel dates, address in France, and host/accommodation should be consistent.'],
                    ['category' => 'Photo', 'label' => 'Recent visa photos', 'help_text' => 'Use current photos that satisfy filing-center specifications.'],
                    ['category' => 'Travel', 'label' => 'Round-trip itinerary', 'help_text' => 'Proposed entry and exit travel reflecting the stay plan.'],
                    ['category' => 'Stay', 'label' => 'Accommodation or host invitation', 'help_text' => 'Hotel confirmation or private host support documents.'],
                    ['category' => 'Financial', 'label' => 'Financial support evidence', 'help_text' => 'Recent bank activity, salary documents, or sponsor evidence.'],
                    ['category' => 'Insurance', 'label' => 'Travel medical insurance', 'help_text' => 'Policy should cover the intended Schengen stay.'],
                    ['category' => 'Purpose', 'label' => 'Purpose-specific supporting documents', 'help_text' => 'Business invitation, conference letter, family relationship proof, or tourism plan.'],
                ],
            ],
            [
                'region' => 'Europe',
                'country_name' => 'Spain',
                'visa_type' => 'Short-stay visa',
                'visa_code' => 'C',
                'label' => 'Spain short-stay operational checklist',
                'description' => 'Short-stay Spain checklist for tourism and other temporary travel, subject to nationality and mission rules.',
                'source_url' => 'https://www.exteriores.gob.es/Consulados/londres/en/ServiciosConsulares/Paginas/Consular/Visados-Schengen.aspx',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check the responsible Spanish consular post and filing provider before submission.',
                'fee_summary' => null,
                'stay_summary' => 'Short-stay Schengen travel is generally up to 90 days within 180 days.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport and prior visa copies', 'help_text' => 'Confirm passport validity and available pages for visa placement.'],
                    ['category' => 'Application', 'label' => 'Completed short-stay application form', 'help_text' => 'Keep names, dates, and address details aligned across the file.'],
                    ['category' => 'Photo', 'label' => 'Recent passport photos', 'help_text' => 'Prepare photos to the filing-center specification.'],
                    ['category' => 'Travel', 'label' => 'Travel itinerary and bookings', 'help_text' => 'Flights and accommodation consistent with planned stay.'],
                    ['category' => 'Financial', 'label' => 'Proof of funds', 'help_text' => 'Recent account statements or sponsor support documents.'],
                    ['category' => 'Insurance', 'label' => 'Travel medical insurance', 'help_text' => 'Coverage should satisfy Schengen requirements.'],
                    ['category' => 'Employment', 'label' => 'Employment or study confirmation', 'help_text' => 'Evidence of ongoing work, study, or business ties.'],
                ],
            ],
            [
                'region' => 'Europe',
                'country_name' => 'Italy',
                'visa_type' => 'Study visa',
                'visa_code' => 'D',
                'label' => 'Italy study visa operational checklist',
                'description' => 'Long-stay study checklist for applicants heading to Italy for university or other approved study.',
                'source_url' => 'https://vistoperitalia.esteri.it/home/en',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Review consular guidance and local filing requirements before submission.',
                'fee_summary' => null,
                'stay_summary' => 'Long-stay national visa conditions depend on study length and residence permit requirements.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Check validity and blank pages for national visa issuance.'],
                    ['category' => 'Education', 'label' => 'Admission or enrolment letter', 'help_text' => 'University or approved institution acceptance documentation.'],
                    ['category' => 'Financial', 'label' => 'Financial support evidence', 'help_text' => 'Funds for tuition, living costs, and return travel.'],
                    ['category' => 'Stay', 'label' => 'Accommodation evidence', 'help_text' => 'Dormitory booking, lease, or host arrangement.'],
                    ['category' => 'Insurance', 'label' => 'Health coverage evidence', 'help_text' => 'Insurance or health arrangement as required by the mission.'],
                    ['category' => 'Background', 'label' => 'Academic history bundle', 'help_text' => 'Transcripts, diplomas, and supporting study background documents.'],
                ],
            ],
            [
                'region' => 'Europe',
                'country_name' => 'Ireland',
                'visa_type' => 'Short Stay Visit visa',
                'visa_code' => 'C',
                'label' => 'Ireland short stay visit operational checklist',
                'description' => 'Short stay visit checklist for family, tourism, or friend visits to Ireland.',
                'source_url' => 'https://www.irishimmigration.ie/coming-to-visit-ireland/how-to-apply-for-a-short-stay-c-visit-tourist-visa/visit-family-friend-visa/',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check Irish Immigration guidance and local office timelines before filing.',
                'fee_summary' => null,
                'stay_summary' => 'Short stay C visit permission is generally for up to 90 days.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use a current passport scan with previous visas if relevant.'],
                    ['category' => 'Purpose', 'label' => 'Visit purpose letter', 'help_text' => 'Explain why the applicant is visiting and for how long.'],
                    ['category' => 'Sponsor', 'label' => 'Host invitation or relationship proof', 'help_text' => 'Add host identity and relationship evidence when applicable.'],
                    ['category' => 'Travel', 'label' => 'Travel and stay plan', 'help_text' => 'Outline intended travel dates and accommodation details.'],
                    ['category' => 'Financial', 'label' => 'Financial support evidence', 'help_text' => 'Bank statements, salary proof, or host support documents.'],
                    ['category' => 'Employment', 'label' => 'Home-country ties evidence', 'help_text' => 'Employment, study, or family ties supporting return intent.'],
                ],
            ],
            [
                'region' => 'Europe',
                'country_name' => 'United Kingdom',
                'visa_type' => 'Standard Visitor visa',
                'visa_code' => null,
                'label' => 'United Kingdom standard visitor operational checklist',
                'description' => 'Short visit checklist for tourism, family visit, and limited business activities.',
                'source_url' => 'https://www.gov.uk/standard-visitor',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check GOV.UK for the latest processing and appointment expectations.',
                'fee_summary' => null,
                'stay_summary' => 'Standard Visitor permission is generally for visits up to 6 months.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use a readable colour scan and note any previous UK visas.'],
                    ['category' => 'Purpose', 'label' => 'Visit purpose statement', 'help_text' => 'Summarise reason for travel and planned activities in the UK.'],
                    ['category' => 'Travel', 'label' => 'Travel itinerary and accommodation plan', 'help_text' => 'Outline intended travel dates and where the applicant will stay.'],
                    ['category' => 'Financial', 'label' => 'Bank statements or financial support evidence', 'help_text' => 'Show ability to fund the trip without prohibited work.'],
                    ['category' => 'Employment', 'label' => 'Employment, study, or business ties evidence', 'help_text' => 'Support the applicant’s return intention after the visit.'],
                    ['category' => 'Sponsor', 'label' => 'Host invitation if applicable', 'help_text' => 'Include the inviter’s identity, immigration status, and accommodation details when relevant.'],
                    ['category' => 'History', 'label' => 'Previous travel and immigration history reviewed', 'help_text' => 'Flag refusals, overstays, or other history that may require explanation.'],
                ],
            ],
            [
                'region' => 'Europe',
                'country_name' => 'United Kingdom',
                'visa_type' => 'Student visa',
                'visa_code' => null,
                'label' => 'United Kingdom student visa operational checklist',
                'description' => 'Study visa workflow for applicants with UK sponsorship and course acceptance.',
                'source_url' => 'https://www.gov.uk/student-visa',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check GOV.UK and the applicant’s filing location for timing and biometrics requirements.',
                'fee_summary' => null,
                'stay_summary' => 'Length of stay depends on course dates and student permission granted.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use a clear current passport scan.'],
                    ['category' => 'Sponsorship', 'label' => 'CAS details reviewed', 'help_text' => 'Check course, sponsor licence details, and issue timing of the CAS.'],
                    ['category' => 'Financial', 'label' => 'Tuition and maintenance evidence', 'help_text' => 'Ensure maintenance and any required funds evidence are ready if applicable.'],
                    ['category' => 'Education', 'label' => 'Academic documents used for CAS', 'help_text' => 'Collect transcripts, certificates, or provider documents used by the sponsor.'],
                    ['category' => 'English', 'label' => 'English language requirement reviewed', 'help_text' => 'Confirm whether separate evidence is needed for the applicant.'],
                    ['category' => 'Health', 'label' => 'Immigration health surcharge and TB review', 'help_text' => 'Check IHS, TB test requirements, and other location-specific items.'],
                ],
            ],
            [
                'region' => 'Europe',
                'country_name' => 'United Kingdom',
                'visa_type' => 'Skilled Worker visa',
                'visa_code' => null,
                'label' => 'United Kingdom skilled worker operational checklist',
                'description' => 'Employer-sponsored work visa workflow for applicants using the Skilled Worker route.',
                'source_url' => 'https://www.gov.uk/skilled-worker-visa',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Review GOV.UK for current sponsorship, salary, and timing rules.',
                'fee_summary' => null,
                'stay_summary' => 'Stay period depends on the certificate of sponsorship and permission granted.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Current passport plus relevant immigration history if available.'],
                    ['category' => 'Sponsorship', 'label' => 'Certificate of Sponsorship details', 'help_text' => 'Review sponsor, occupation code, and work location details.'],
                    ['category' => 'Employment', 'label' => 'Salary and role eligibility review', 'help_text' => 'Check the salary level and job suitability against route rules.'],
                    ['category' => 'Financial', 'label' => 'Maintenance arrangement', 'help_text' => 'Confirm whether maintenance is certified or separately evidenced.'],
                    ['category' => 'English', 'label' => 'English language evidence or exemption', 'help_text' => 'Capture test results or the relevant exemption basis.'],
                    ['category' => 'Health', 'label' => 'TB and immigration health surcharge review', 'help_text' => 'Review location-based TB needs and IHS payment obligations.'],
                ],
            ],
            [
                'region' => 'Asia',
                'country_name' => 'Japan',
                'visa_type' => 'Temporary visitor visa',
                'visa_code' => null,
                'label' => 'Japan temporary visitor operational checklist',
                'description' => 'Short-term tourism/business/family visit intake aligned to Japan visa and eVISA guidance where available.',
                'source_url' => 'https://www.mofa.go.jp/j_info/visit/visa/index.html',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Confirm whether the applicant uses embassy filing or eVISA based on residence and nationality.',
                'fee_summary' => null,
                'stay_summary' => 'Short-term temporary visitor travel is generally limited to a short stay for tourism or similar purposes.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use current passport and any prior Japanese visa pages if relevant.'],
                    ['category' => 'Application', 'label' => 'Visa application or eVISA intake reviewed', 'help_text' => 'Confirm the correct filing channel for the applicant’s location and nationality.'],
                    ['category' => 'Photo', 'label' => 'Recent passport photo', 'help_text' => 'Prepare a compliant photo for mission or eVISA submission.'],
                    ['category' => 'Travel', 'label' => 'Flight and stay itinerary', 'help_text' => 'Outline flights, accommodation, and day-by-day or summary travel plan.'],
                    ['category' => 'Financial', 'label' => 'Financial proof', 'help_text' => 'Bank statements or sponsor evidence showing the trip can be funded.'],
                    ['category' => 'Employment', 'label' => 'Employment or school certificate', 'help_text' => 'Show the applicant’s current status and home-country ties.'],
                    ['category' => 'Sponsor', 'label' => 'Guarantor or host documents if applicable', 'help_text' => 'Collect invitation and identity documents for hosted travel where needed.'],
                ],
            ],
            [
                'region' => 'Asia',
                'country_name' => 'Japan',
                'visa_type' => 'Student visa',
                'visa_code' => null,
                'label' => 'Japan student visa operational checklist',
                'description' => 'Study visa workflow for applicants joining language school, university, or other approved education in Japan.',
                'source_url' => 'https://www.mofa.go.jp/j_info/visit/visa/index.html',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Check mission guidance and the school’s certificate of eligibility workflow before filing.',
                'fee_summary' => null,
                'stay_summary' => 'Length of stay depends on status of residence and school sponsorship.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use the current passport and confirm validity.'],
                    ['category' => 'Education', 'label' => 'Certificate of Eligibility or school issuance plan', 'help_text' => 'Track whether the Japanese sponsor will obtain the COE first.'],
                    ['category' => 'Education', 'label' => 'Admission letter and course details', 'help_text' => 'Collect acceptance documents and program schedule.'],
                    ['category' => 'Financial', 'label' => 'Financial support evidence', 'help_text' => 'Document applicant or sponsor funds for tuition and living costs.'],
                    ['category' => 'Background', 'label' => 'Academic history and study plan', 'help_text' => 'Gather transcripts and a short rationale for study in Japan.'],
                    ['category' => 'Sponsor', 'label' => 'Sponsor documents if funded by another person', 'help_text' => 'Identity, relationship, and financial proof for the sponsor.'],
                ],
            ],
            [
                'region' => 'Asia',
                'country_name' => 'South Korea',
                'visa_type' => 'Short-term tourism entry',
                'visa_code' => 'C-3-9',
                'label' => 'South Korea short-term tourism operational checklist',
                'description' => 'Operational checklist for short-term tourism entry, which may involve K-ETA or visa processing depending on nationality.',
                'source_url' => 'https://www.visa.go.kr/',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'First confirm whether the traveller needs a visa, can use K-ETA, or is visa-exempt.',
                'fee_summary' => null,
                'stay_summary' => 'Allowed stay and filing route depend on nationality and approved entry permission.',
                'items' => [
                    ['category' => 'Eligibility', 'label' => 'Visa vs K-ETA eligibility confirmed', 'help_text' => 'Document whether the traveller needs a visa, K-ETA, or no advance approval.'],
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Current passport should match any online pre-clearance or application record.'],
                    ['category' => 'Application', 'label' => 'Visa portal or K-ETA intake reviewed', 'help_text' => 'Use the correct filing path based on nationality and travel purpose.'],
                    ['category' => 'Travel', 'label' => 'Travel itinerary and stay plan', 'help_text' => 'Flights, accommodation, and intended trip outline.'],
                    ['category' => 'Financial', 'label' => 'Financial proof', 'help_text' => 'Bank statements or sponsor support if requested by the filing channel.'],
                    ['category' => 'Employment', 'label' => 'Employment or school evidence', 'help_text' => 'Support ties to the home country and return plan.'],
                ],
            ],
            [
                'region' => 'Asia',
                'country_name' => 'Singapore',
                'visa_type' => 'Business / visit visa',
                'visa_code' => null,
                'label' => 'Singapore business or visit operational checklist',
                'description' => 'Short business or visit intake aligned with visa-required traveller workflows and ICA entry rules.',
                'source_url' => 'https://www.ica.gov.sg/enter-transit-depart/entering-singapore/visa_requirements',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Verify whether the traveller’s passport requires a visa and whether extra supporting documents are needed.',
                'fee_summary' => null,
                'stay_summary' => 'The length of stay is determined by the immigration pass issued at entry, not by visa validity alone.',
                'items' => [
                    ['category' => 'Eligibility', 'label' => 'Visa-required nationality confirmed', 'help_text' => 'Check whether the travel document requires advance visa issuance.'],
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use a current passport scan and any prior Singapore travel records if relevant.'],
                    ['category' => 'Application', 'label' => 'Application form and local contact details', 'help_text' => 'Ensure the visa application reflects the local contact or host details correctly.'],
                    ['category' => 'Purpose', 'label' => 'Business or visit supporting letter', 'help_text' => 'Invitation, company letter, or visit explanation depending on travel purpose.'],
                    ['category' => 'Travel', 'label' => 'Flight and accommodation plan', 'help_text' => 'Document travel dates and intended place of stay in Singapore.'],
                    ['category' => 'Financial', 'label' => 'Financial support evidence if requested', 'help_text' => 'Prepare bank or sponsor documents for applicants asked to provide them.'],
                ],
            ],
            [
                'region' => 'Asia',
                'country_name' => 'Thailand',
                'visa_type' => 'Tourist eVisa',
                'visa_code' => 'TR',
                'label' => 'Thailand tourist eVisa operational checklist',
                'description' => 'Tourist travel checklist for applicants using Thailand eVisa or consular tourist filing routes.',
                'source_url' => 'https://www.thaievisa.go.th/',
                'source_checked_at' => $sourceCheckedAt,
                'processing_time_summary' => 'Official eVisa guidance should be checked for current processing and nationality coverage.',
                'fee_summary' => null,
                'stay_summary' => 'Tourist stay length and entry conditions depend on the visa class and current Thai immigration policy.',
                'items' => [
                    ['category' => 'Identity', 'label' => 'Passport biodata page', 'help_text' => 'Use a clear scan and verify validity for intended travel.'],
                    ['category' => 'Application', 'label' => 'Thailand eVisa application reviewed', 'help_text' => 'Confirm the correct visa class and current eligible filing channel.'],
                    ['category' => 'Photo', 'label' => 'Recent digital photo', 'help_text' => 'Prepare a compliant image for online filing.'],
                    ['category' => 'Travel', 'label' => 'Return or onward travel booking', 'help_text' => 'Provide travel evidence that matches intended stay dates.'],
                    ['category' => 'Stay', 'label' => 'Accommodation evidence', 'help_text' => 'Hotel booking or host address for the stay period.'],
                    ['category' => 'Financial', 'label' => 'Financial proof', 'help_text' => 'Recent account evidence for the required maintenance level.'],
                    ['category' => 'Purpose', 'label' => 'Tourism purpose explanation if needed', 'help_text' => 'Keep a short travel plan ready for file clarity.'],
                ],
            ],
        ];

        foreach ($templates as $templateData) {
            $items = $templateData['items'];
            unset($templateData['items']);

            $templateData['requires_institution_name'] ??=
                str_contains(strtolower($templateData['visa_type']), 'student')
                || str_contains(strtolower($templateData['visa_type']), 'study');

            $template = VisaRequirementTemplate::query()->updateOrCreate(
                [
                    'country_name' => $templateData['country_name'],
                    'visa_type' => $templateData['visa_type'],
                ],
                $templateData,
            );

            foreach ($items as $index => $item) {
                $template->items()->updateOrCreate(
                    ['sort_order' => $index + 1],
                    [
                        'category' => $item['category'] ?? null,
                        'label' => $item['label'],
                        'help_text' => $item['help_text'] ?? null,
                        'is_required' => $item['is_required'] ?? true,
                    ],
                );
            }

            $template->items()
                ->where('sort_order', '>', count($items))
                ->delete();
        }
    }
}
